// Generated by delombok at Tue Jul 03 21:12:42 NOVT 2018
package org.statesync.spring.demo.entity;

import java.util.List;
import javax.validation.constraints.NotNull;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * Collection of sync areas
 *
 * @author ify
 */
@Document
public class UserProfile {
	/**
	 * Unique id of stay sync area
	 */
	@Id
	public String id;
	@NotNull
	public String email;
	@NotNull
	public String password;
	@NotNull
	public String fullName;
	@NotNull
	private List<Role> roles;

	@java.lang.SuppressWarnings("all")
	public UserProfile() {
	}

	/**
	 * Unique id of stay sync area
	 */
	@java.lang.SuppressWarnings("all")
	public String getId() {
		return this.id;
	}

	@java.lang.SuppressWarnings("all")
	public String getEmail() {
		return this.email;
	}

	@java.lang.SuppressWarnings("all")
	public String getPassword() {
		return this.password;
	}

	@java.lang.SuppressWarnings("all")
	public String getFullName() {
		return this.fullName;
	}

	@java.lang.SuppressWarnings("all")
	public List<Role> getRoles() {
		return this.roles;
	}

	/**
	 * Unique id of stay sync area
	 */
	@java.lang.SuppressWarnings("all")
	public void setId(final String id) {
		this.id = id;
	}

	@java.lang.SuppressWarnings("all")
	public void setEmail(final String email) {
		this.email = email;
	}

	@java.lang.SuppressWarnings("all")
	public void setPassword(final String password) {
		this.password = password;
	}

	@java.lang.SuppressWarnings("all")
	public void setFullName(final String fullName) {
		this.fullName = fullName;
	}

	@java.lang.SuppressWarnings("all")
	public void setRoles(final List<Role> roles) {
		this.roles = roles;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof UserProfile)) return false;
		final UserProfile other = (UserProfile) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$id = this.getId();
		final java.lang.Object other$id = other.getId();
		if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
		final java.lang.Object this$email = this.getEmail();
		final java.lang.Object other$email = other.getEmail();
		if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
		final java.lang.Object this$password = this.getPassword();
		final java.lang.Object other$password = other.getPassword();
		if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
		final java.lang.Object this$fullName = this.getFullName();
		final java.lang.Object other$fullName = other.getFullName();
		if (this$fullName == null ? other$fullName != null : !this$fullName.equals(other$fullName)) return false;
		final java.lang.Object this$roles = this.getRoles();
		final java.lang.Object other$roles = other.getRoles();
		if (this$roles == null ? other$roles != null : !this$roles.equals(other$roles)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof UserProfile;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $id = this.getId();
		result = result * PRIME + ($id == null ? 43 : $id.hashCode());
		final java.lang.Object $email = this.getEmail();
		result = result * PRIME + ($email == null ? 43 : $email.hashCode());
		final java.lang.Object $password = this.getPassword();
		result = result * PRIME + ($password == null ? 43 : $password.hashCode());
		final java.lang.Object $fullName = this.getFullName();
		result = result * PRIME + ($fullName == null ? 43 : $fullName.hashCode());
		final java.lang.Object $roles = this.getRoles();
		result = result * PRIME + ($roles == null ? 43 : $roles.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "UserProfile(id=" + this.getId() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", fullName=" + this.getFullName() + ", roles=" + this.getRoles() + ")";
	}
}
