// Generated by delombok at Tue Jul 03 21:12:42 NOVT 2018
package org.statesync.spring.demo.sync.dashboard;

import java.util.Arrays;
import java.util.List;

public class ChartData {
	public List<String> labels = Arrays.asList("January", "February", "March", "April", "May", "June", "July");
	public List<DataSet> datasets = Arrays.asList(new DataSet());

	@java.lang.SuppressWarnings("all")
	public ChartData() {
	}

	@java.lang.SuppressWarnings("all")
	public List<String> getLabels() {
		return this.labels;
	}

	@java.lang.SuppressWarnings("all")
	public List<DataSet> getDatasets() {
		return this.datasets;
	}

	@java.lang.SuppressWarnings("all")
	public void setLabels(final List<String> labels) {
		this.labels = labels;
	}

	@java.lang.SuppressWarnings("all")
	public void setDatasets(final List<DataSet> datasets) {
		this.datasets = datasets;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ChartData)) return false;
		final ChartData other = (ChartData) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$labels = this.getLabels();
		final java.lang.Object other$labels = other.getLabels();
		if (this$labels == null ? other$labels != null : !this$labels.equals(other$labels)) return false;
		final java.lang.Object this$datasets = this.getDatasets();
		final java.lang.Object other$datasets = other.getDatasets();
		if (this$datasets == null ? other$datasets != null : !this$datasets.equals(other$datasets)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof ChartData;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $labels = this.getLabels();
		result = result * PRIME + ($labels == null ? 43 : $labels.hashCode());
		final java.lang.Object $datasets = this.getDatasets();
		result = result * PRIME + ($datasets == null ? 43 : $datasets.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "ChartData(labels=" + this.getLabels() + ", datasets=" + this.getDatasets() + ")";
	}
}
