// Generated by delombok at Tue Jul 03 21:12:42 NOVT 2018
package org.statesync.spring.demo.sync.dashboard;

public class DashboardModel {
	public final DashboardSettings settings = new DashboardSettings();
	public String name;
	public LinearChart chart1 = new LinearChart();
	public int membersOnline;

	@java.lang.SuppressWarnings("all")
	public DashboardModel() {
	}

	@java.lang.SuppressWarnings("all")
	public DashboardSettings getSettings() {
		return this.settings;
	}

	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}

	@java.lang.SuppressWarnings("all")
	public LinearChart getChart1() {
		return this.chart1;
	}

	@java.lang.SuppressWarnings("all")
	public int getMembersOnline() {
		return this.membersOnline;
	}

	@java.lang.SuppressWarnings("all")
	public void setName(final String name) {
		this.name = name;
	}

	@java.lang.SuppressWarnings("all")
	public void setChart1(final LinearChart chart1) {
		this.chart1 = chart1;
	}

	@java.lang.SuppressWarnings("all")
	public void setMembersOnline(final int membersOnline) {
		this.membersOnline = membersOnline;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof DashboardModel)) return false;
		final DashboardModel other = (DashboardModel) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$settings = this.getSettings();
		final java.lang.Object other$settings = other.getSettings();
		if (this$settings == null ? other$settings != null : !this$settings.equals(other$settings)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		final java.lang.Object this$chart1 = this.getChart1();
		final java.lang.Object other$chart1 = other.getChart1();
		if (this$chart1 == null ? other$chart1 != null : !this$chart1.equals(other$chart1)) return false;
		if (this.getMembersOnline() != other.getMembersOnline()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof DashboardModel;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $settings = this.getSettings();
		result = result * PRIME + ($settings == null ? 43 : $settings.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 43 : $name.hashCode());
		final java.lang.Object $chart1 = this.getChart1();
		result = result * PRIME + ($chart1 == null ? 43 : $chart1.hashCode());
		result = result * PRIME + this.getMembersOnline();
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "DashboardModel(settings=" + this.getSettings() + ", name=" + this.getName() + ", chart1=" + this.getChart1() + ", membersOnline=" + this.getMembersOnline() + ")";
	}
}
