// Generated by delombok at Tue Jul 03 21:12:42 NOVT 2018
package org.statesync.spring.demo.sync.dashboard;

public class LinearChart {
	public ChartData data = new ChartData();

	@java.lang.SuppressWarnings("all")
	public LinearChart() {
	}

	@java.lang.SuppressWarnings("all")
	public ChartData getData() {
		return this.data;
	}

	@java.lang.SuppressWarnings("all")
	public void setData(final ChartData data) {
		this.data = data;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof LinearChart)) return false;
		final LinearChart other = (LinearChart) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$data = this.getData();
		final java.lang.Object other$data = other.getData();
		if (this$data == null ? other$data != null : !this$data.equals(other$data)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof LinearChart;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $data = this.getData();
		result = result * PRIME + ($data == null ? 43 : $data.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "LinearChart(data=" + this.getData() + ")";
	}
}
