// Generated by delombok at Tue Jul 03 21:12:42 NOVT 2018
package org.statesync.spring.demo.sync.debug;

import org.statesync.info.StateSyncInfo;

public class StateSyncInfoModel {
	public StateSyncInfo info = new StateSyncInfo();

	@java.lang.SuppressWarnings("all")
	public StateSyncInfoModel() {
	}

	@java.lang.SuppressWarnings("all")
	public StateSyncInfo getInfo() {
		return this.info;
	}

	@java.lang.SuppressWarnings("all")
	public void setInfo(final StateSyncInfo info) {
		this.info = info;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof StateSyncInfoModel)) return false;
		final StateSyncInfoModel other = (StateSyncInfoModel) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$info = this.getInfo();
		final java.lang.Object other$info = other.getInfo();
		if (this$info == null ? other$info != null : !this$info.equals(other$info)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof StateSyncInfoModel;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $info = this.getInfo();
		result = result * PRIME + ($info == null ? 43 : $info.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "StateSyncInfoModel(info=" + this.getInfo() + ")";
	}
}
