// Generated by delombok at Tue Jul 03 21:12:42 NOVT 2018
package org.statesync.spring.demo.sync.tasks;

import org.statesync.model.permissions.ItemCrudPermissions;

public class TaskPermissions extends ItemCrudPermissions {
	public static final TaskPermissions ALL = new TaskPermissions();
	public static final TaskPermissions READONLY = new TaskPermissions();
	public static final TaskPermissions EDIT = new TaskPermissions();

	static {
		ALL.delete = true;
		ALL.edit = true;
		EDIT.delete = false;
		EDIT.edit = true;
		READONLY.delete = false;
		READONLY.edit = false;
	}

	@java.lang.SuppressWarnings("all")
	public TaskPermissions() {
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "TaskPermissions()";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof TaskPermissions)) return false;
		final TaskPermissions other = (TaskPermissions) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof TaskPermissions;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		int result = super.hashCode();
		return result;
	}
}
