// Generated by delombok at Tue Jul 03 21:12:42 NOVT 2018
package org.statesync.spring.demo.sync.tasks;

import org.statesync.model.AnnotatedItem;
import org.statesync.model.AnnotatedList;
import org.statesync.model.ListQuery;

public class TasksModel {
	public ListQuery query = new ListQuery();
	public NewTaskForm newTask = new NewTaskForm();
	public AnnotatedItem<EditTaskForm, TaskPermissions> editTask;
	public AnnotatedList<TaskRow, TaskPermissions, TaskListPermissions> items = new AnnotatedList<>();

	@java.lang.SuppressWarnings("all")
	public TasksModel() {
	}

	@java.lang.SuppressWarnings("all")
	public ListQuery getQuery() {
		return this.query;
	}

	@java.lang.SuppressWarnings("all")
	public NewTaskForm getNewTask() {
		return this.newTask;
	}

	@java.lang.SuppressWarnings("all")
	public AnnotatedItem<EditTaskForm, TaskPermissions> getEditTask() {
		return this.editTask;
	}

	@java.lang.SuppressWarnings("all")
	public AnnotatedList<TaskRow, TaskPermissions, TaskListPermissions> getItems() {
		return this.items;
	}

	@java.lang.SuppressWarnings("all")
	public void setQuery(final ListQuery query) {
		this.query = query;
	}

	@java.lang.SuppressWarnings("all")
	public void setNewTask(final NewTaskForm newTask) {
		this.newTask = newTask;
	}

	@java.lang.SuppressWarnings("all")
	public void setEditTask(final AnnotatedItem<EditTaskForm, TaskPermissions> editTask) {
		this.editTask = editTask;
	}

	@java.lang.SuppressWarnings("all")
	public void setItems(final AnnotatedList<TaskRow, TaskPermissions, TaskListPermissions> items) {
		this.items = items;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof TasksModel)) return false;
		final TasksModel other = (TasksModel) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		final java.lang.Object this$query = this.getQuery();
		final java.lang.Object other$query = other.getQuery();
		if (this$query == null ? other$query != null : !this$query.equals(other$query)) return false;
		final java.lang.Object this$newTask = this.getNewTask();
		final java.lang.Object other$newTask = other.getNewTask();
		if (this$newTask == null ? other$newTask != null : !this$newTask.equals(other$newTask)) return false;
		final java.lang.Object this$editTask = this.getEditTask();
		final java.lang.Object other$editTask = other.getEditTask();
		if (this$editTask == null ? other$editTask != null : !this$editTask.equals(other$editTask)) return false;
		final java.lang.Object this$items = this.getItems();
		final java.lang.Object other$items = other.getItems();
		if (this$items == null ? other$items != null : !this$items.equals(other$items)) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof TasksModel;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final java.lang.Object $query = this.getQuery();
		result = result * PRIME + ($query == null ? 43 : $query.hashCode());
		final java.lang.Object $newTask = this.getNewTask();
		result = result * PRIME + ($newTask == null ? 43 : $newTask.hashCode());
		final java.lang.Object $editTask = this.getEditTask();
		result = result * PRIME + ($editTask == null ? 43 : $editTask.hashCode());
		final java.lang.Object $items = this.getItems();
		result = result * PRIME + ($items == null ? 43 : $items.hashCode());
		return result;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "TasksModel(query=" + this.getQuery() + ", newTask=" + this.getNewTask() + ", editTask=" + this.getEditTask() + ", items=" + this.getItems() + ")";
	}
}
