// Generated by delombok at Tue Jul 03 21:12:42 NOVT 2018
package org.statesync.spring.demo.sync.tasks;

import org.statesync.model.permissions.ListCrudPermissions;

public class TaskListPermissions extends ListCrudPermissions {
	public boolean batchDelete;

	public TaskListPermissions() {
		this.create = true;
		this.delete = true;
	}

	@java.lang.SuppressWarnings("all")
	public boolean isBatchDelete() {
		return this.batchDelete;
	}

	@java.lang.SuppressWarnings("all")
	public void setBatchDelete(final boolean batchDelete) {
		this.batchDelete = batchDelete;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "TaskListPermissions(batchDelete=" + this.isBatchDelete() + ")";
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof TaskListPermissions)) return false;
		final TaskListPermissions other = (TaskListPermissions) o;
		if (!other.canEqual((java.lang.Object) this)) return false;
		if (!super.equals(o)) return false;
		if (this.isBatchDelete() != other.isBatchDelete()) return false;
		return true;
	}

	@java.lang.SuppressWarnings("all")
	protected boolean canEqual(final java.lang.Object other) {
		return other instanceof TaskListPermissions;
	}

	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 59;
		int result = super.hashCode();
		result = result * PRIME + (this.isBatchDelete() ? 79 : 97);
		return result;
	}
}
